apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: existingsa-feb27
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: existingsa-feb27
  name: existingsa-feb27
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: existingsa-feb27
